app/main/routes.py
import os
import re
from flask import Blueprint, current_app, render_template, render_template_string, send_from_directory, url_for
from app import app
import markdown


main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home_page():

    '''
    View root page function that returns the index page and its data
    '''
    return render_template('main/home.html')

@main.route('/about')
def about():
    return render_template('main/about.html')

def get_readme_content():
    base_dir = os.path.dirname(current_app.root_path)
    readme_path = os.path.join(base_dir, 'doc', 'README.md')
    try:
        with open(readme_path, 'r') as file:
            content = file.read()
        return content
    except FileNotFoundError:
        return "README.md not found in /doc directory."

def fix_image_paths(html_content):
    def repl(match):
        img_src = match.group(1)
        new_src = url_for('main.serve_doc_file', filename=img_src)
        return f'<img src="{new_src}"'
    
    pattern = r'<img src="([^"]+)"'
    return re.sub(pattern, repl, html_content)

@main.route('/documentation')
def display_readme():
    readme_content = get_readme_content()
    
    # Convert markdown to HTML
    html_content = markdown.markdown(readme_content)
    
    # Fix image paths
    html_content = fix_image_paths(html_content)
    
    # Debug: Print the HTML content
    print("HTML Content:", html_content)
    
    return render_template('main/documentation.html', content=html_content)

@main.route('/doc/<path:filename>')
def serve_doc_file(filename):
    base_dir = os.path.dirname(current_app.root_path)
    doc_dir = os.path.join(base_dir, 'doc')
    
    # Debug: Print the requested filename and full path
    full_path = os.path.join(doc_dir, filename)
    print(f"Requested file: {filename}")
    print(f"Full path: {full_path}")
    print(f"File exists: {os.path.exists(full_path)}")
    
    return send_from_directory(doc_dir, filename)

app/posts/routes.py
from flask import Blueprint, current_app, render_template, redirect, session, url_for, request, flash
from flask_login import current_user, login_required
from app.posts.models import Crime, Message
from app import db, send_admin_email
from werkzeug.utils import secure_filename

posts = Blueprint('posts', __name__)


# submitting crime report
@posts.route('/crime_report', methods=['GET', 'POST'])
def report_crime():

    reporter = current_user.id

    # Gettting location from session
    latitude = session.get('latitude')
    longitude = session.get('longitude')

    if request.method == 'POST':
        date_of_incident = request.form.get('date_of_incident')
        issued_by = request.form.get('issued_by')
        time_of_incident = request.form.get('time_of_incident')
        phonenumber = request.form.get('phonenumber')
        incident_location = request.form.get('incident_location')
        incident_nature = request.form.get('incident_nature')
        incident_details = request.form.get('incident_details')
        suspect_details = request.form.get('suspect_details')
        arrest_history = request.form.get('arrest_history')
        suspect_name = request.form.get('suspect_name')
        comments = request.form.get('comments')
        image = request.files['image']


        filename = secure_filename(image.filename)
        mimetype = image.mimetype


        
        if date_of_incident == '':
            flash('Date when incident occurred cannot be empty', category='warning')
        elif len(phonenumber) < 10 or len(phonenumber) > 10:
            flash('Invalid Phone number', category='warning')
        elif time_of_incident == '':
            flash('Time when incident occurred cannot be empty', category='warning')
        elif incident_location == '':
            flash('Incident location cannot be empty', category='warning')
        elif incident_nature == '':
            flash('Nature of incident cannot be empty', category='warning')
        elif incident_details == '':
            flash('Incident details cannot be empty', category='warning')
        else:
            crime_report = Crime(date_of_incident=date_of_incident, 
                                    issued_by=issued_by,
                                    time_of_incident=time_of_incident, 
                                    phonenumber=phonenumber,
                                    incident_location=incident_location,
                                    incident_nature=incident_nature, 
                                    incident_details=incident_details,
                                    suspect_details=suspect_details, 
                                    arrest_history=arrest_history,
                                    suspect_name=suspect_name,
                                    comments=comments,
                                    latitude=latitude,
                                    longitude=longitude,
                                    crime_file_upload=image.read(),
                                    crime_file_name=filename,
                                    crime_mimetype=mimetype,
                                    reporter_id=reporter)
            try:
                db.session.add(crime_report)
                db.session.commit()

                #sending email
                subject = f"New Crime Report Sent: {crime_report.incident_nature}"
                body = f"""
                    A new theft report has been sent:

                    Location: {crime_report.incident_location}
                    Date: {crime_report.date_of_incident}
                    Time: {crime_report.time_of_incident}

                    Please review this report as soon as possible.
                """
                if send_admin_email(subject, body):
                    flash("Report submitted successfully and admin has been notified.", "success")
                else:
                    flash("Report submitted successfully, but there was an issue notifying the admin.", "warning")

                return redirect(url_for('users.user_dashboard'))
            except Exception:
                current_app.logger.error("Database error:")
                flash(f"An error occurred! Please try again", category='danger')
                return render_template('user/report_crime.html')
        
    return render_template('user/report_crime.html')

# contact us
@posts.route('/users/contactus', methods=["POST","GET"])
@login_required
def contact_us():
    sender = current_user.id

    if request.method == 'POST':
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        email = request.form.get('email')
        message = request.form.get('message')

        sender_message = Message(
            first_name=firstName,
            last_name=lastName,
            email_address=email,
            message=message,
            sender_id=sender
        )
        try:
            db.session.add(sender_message)
            db.session.commit()

            subject = f"New Message Sent"
            body = f"""
                You have a new message from: {sender_message.first_name}
            """
            if send_admin_email(subject, body):
                flash("Message sent successfully wait for feedback from admin.", "success")
            else:
                flash("Message sent successfully, but there was an issue notifying the admin.", "warning")

            return redirect(url_for('posts.contact_us'))
        except Exception:
            current_app.logger.error("Database error:")
            flash(f"An error occurred! Please try again", category='danger')
            return render_template('user/contactus.html')
        
    return render_template('/user/contactus.html')

@posts.route('/quick_crime_report', methods=['GET', 'POST'])
def quick_report():

    if request.method == 'POST':
        date_of_incident = request.form.get('date_of_incident')
        latitude = request.form.get('latitude')
        longitude = request.form.get('longitude')
        time_of_incident = request.form.get('time_of_incident')
        phonenumber = request.form.get('phonenumber')
        incident_location = request.form.get('incident_location')
        incident_nature = request.form.get('incident_nature')
        incident_details = request.form.get('incident_details')
        image = request.files['image']


        filename = secure_filename(image.filename)
        mimetype = image.mimetype

        if date_of_incident == '':
            flash('Date when incident occurred cannot be empty', category='warning')
        elif len(phonenumber) < 10 or len(phonenumber) > 10:
            flash('Invalid Phone number', category='warning')
        elif time_of_incident == '':
            flash('Time when incident occurred cannot be empty', category='warning')
        elif incident_location == '':
            flash('Incident location cannot be empty', category='warning')
        elif incident_nature == '':
            flash('Nature of incident cannot be empty', category='warning')
        elif incident_details == '':
            flash('Incident details cannot be empty', category='warning')
        else:
            crime_report = Crime(date_of_incident=date_of_incident, 
                                    time_of_incident=time_of_incident, 
                                    phonenumber=phonenumber,
                                    incident_location=incident_location,
                                    incident_nature=incident_nature, 
                                    incident_details=incident_details,
                                    latitude=latitude,
                                    longitude=longitude,
                                    crime_file_upload=image.read(),
                                    crime_file_name=filename,
                                    crime_mimetype=mimetype)
            
            
            try:
                db.session.add(crime_report)
                db.session.commit()

                #sending email
                subject = f"New Crime Report Sent: {crime_report.incident_nature}"
                body = f"""
                    A new theft report has been sent:

                    Location: {crime_report.incident_location}
                    Date: {crime_report.date_of_incident}
                    Time: {crime_report.time_of_incident}

                    Please review this report as soon as possible.
                """
                if send_admin_email(subject, body):
                    flash("Report submitted successfully and admin has been notified.", "success")
                else:
                    flash("Report submitted successfully, but there was an issue notifying the admin.", "warning")

                return redirect(url_for('users.sign_in'))
            except Exception:
                current_app.logger.error("Database error:")
                flash(f"An error occurred! Please try again", category='danger')
                return render_template('user/quick-report.html')
    
    return render_template('user/quick-report.html')

app/templates/main/about.html
{% extends "user/base.html" %} {% block title %} About Us {% endblock %} {%
block content %}

<div class="about-container">
  <div class="row">
    <div class="column">
      <div class="card">
        <h2>About Us</h2>
        <p>
          We are committed to creating a safer community for everyone.
          E-Security is a confidential online system designed to empower you to
          report crimes and suspicious activity directly to law enforcement. Our
          user-friendly platform makes reporting crimes easier and faster than
          ever before.
        </p>
      </div>
    </div>
    <div class="column">
      <div class="card">
        <h2>Our Mission</h2>
        <p>
          Leveraging technology to revolutionize crime reporting. We offer a
          secure and innovative platform for efficient reporting and enhanced
          public safety.
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="card">
        <h3>Key Features</h3>
        <ul>
          <li>Simple and secure reporting process</li>
          <li>Option to report anonymously</li>
          <li>Upload photos and videos as evidence (optional)</li>
          <li>Secure platform with encrypted data transmission</li>
        </ul>
      </div>
    </div>
    <div class="column">
      <div class="card">
        <h3>Benefits of Using E-Security</h3>
        <ul>
          <li>Faster response times from law enforcement</li>
          <li>Increased crime solving rates</li>
          <li>Improved public safety for your community</li>
          <li>Option to see recovered items</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="privacy">
    <div class="card">
      <h3>Your Privacy Matters</h3>
      <p>
        We understand the importance of confidentiality when reporting a crime.
        E-Security utilizes robust security measures to ensure your information
        is protected. All communication is encrypted, and we only collect the
        data necessary for effective investigations.
      </p>
      <p>
        Together, we can make a difference. Report crime and suspicious activity
        through E-Security today.
      </p>
    </div>
  </div>
</div>

{% endblock %}

app/templates/main/documentation.html
{% extends "user/base.html" %} {% block title %} About Us {% endblock %} {%
  block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Documentation</title>
    <style>
      body {
        margin-top: 20px;
        margin-left: 10px;
      }
        img {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    {{ content | safe }}
</body>
</html>
{% endblock content %}

app/templates/main/home.html
{% extends "user/base.html" %} {% block title %} Home {% endblock %} {% block
content %}
<style>
  body {
    background-image: url("{{ url_for('static', filename='img/home.png') }}");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    height: 100vh;
    margin: 0;
    color: white; 
  }
  .transparent-section {
    background-color: rgba(
      0,
      0,
      0,
      0.5
    ); 
    padding: 40px;
    border-radius: 10px;
  }
  .brand-img {
    height: 50px; 
    width: auto; 
    border-radius: 50%; 
    object-fit: cover;
  }

  .header-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    margin-top: 20px; 
  }

  .header-container header h1 {
    margin-top: 10px; 
  }

</style>
<div class="header-container">
  <img src="{{ url_for('static', filename='img/logo1.png') }}" alt="E-Security" class="d-inline-block align-top brand-img">
  <br>
  <header>
    <h1>Welcome To E-Security</h1>
  </header>
</div>

<div class="position-relative p-3 p-md-5 m-md-3 text-center">
  <main>
    <section class="transparent-section">
      <h2 class="display-4">Report a Crime. Make Your Community Safer.</h2>
      <p class="lead">
        This online system allows you to report a crime to the authorities
        quickly and easily. Reporting suspicious activity can help prevent
        future crimes and keep your community safe.
      </p>
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('posts.report_crime') }}" class="btn btn-primary"
        >Report a Crime Now</a
      >
      {% else %}
      <a href="{{ url_for('posts.quick_report') }}" class="btn btn-primary"
        >Report a Crime Now</a
      >
      {% endif %}
    </section>
  </main>
</div>
{% endblock %}