app/users/models.py
from flask import current_app
from app import db
from flask_login import UserMixin
from itsdangerous import Serializer


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    crimes = db.relationship('Crime', backref='reporter', lazy=True)
    users = db.relationship('Register', backref='user', uselist=False)
    messages = db.relationship('Message', backref='sender', lazy=True)
    

    def get_reset_token(self):
        s = Serializer(current_app.config['SECRET_KEY'])
        return s.dumps({'user_id': self.id}, salt='password-reset-salt')

    @staticmethod
    def verify_reset_token(token, expires_sec=1800):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token, salt='password-reset-salt', max_age=expires_sec)['user_id']
        except:
            return None
        return User.query.get(user_id)
    


class Register(db.Model, UserMixin):
    idno = db.Column(db.Integer, primary_key=True, nullable=False)
    fullname = db.Column(db.String(100), nullable=False)
    phonenumber = db.Column(db.String(20), nullable=False)
    residence = db.Column(db.String(200), nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    users_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/users/routes.py
import os
from flask import Blueprint, Response, current_app, render_template, redirect, send_from_directory, session, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from app.users.models import User, Register
from app.posts.models import Crime, Message
from app import db, send_confirmation_email, send_reset_email
from os import environ
from requests.exceptions import RequestException
import requests

users = Blueprint('users', __name__)

@users.route('/users/signin', methods=['GET', 'POST'])
def sign_in():
    if  session.get('user_id'):
        return redirect('/users/dashboard')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        
        if user:
            if check_password_hash(user.password, password):
                session['user_id']=user.id
                session['username']=user.username
                flash(f'Logged in successfully! Hello {username}', category='success')
                login_user(user, remember=True)
                return redirect(url_for('users.user_dashboard'))
            else: 
                flash('Incorrect password, try again.', category='danger')
        else:
            flash('Username does not exist.', category='danger')
    
    return render_template('user/signin.html')

@users.route("/users/reset_password", methods=['GET', 'POST'])
def reset_request():
    if request.method == 'POST':
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if user:
            send_reset_email(user)
            flash('An email has been sent with instructions to reset your password.', 'info')
            return redirect(url_for('users.sign_in'))
        else:
            flash('Email does not exist', 'danger')
    return render_template('user/reset_request.html')

@users.route("/users/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    
    if request.method == 'POST':
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        
        if password != confirm_password:
            flash('Passwords do not match.', 'danger')
            return render_template('user/reset_token.html')
        
        if len(password) < 8:
            flash('Password must be at least 8 characters long.', 'danger')
            return render_template('user/reset_token.html')
        
        hashed_password = generate_password_hash(password)
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! Please log in', 'success')
        return redirect(url_for('users.sign_in'))
    
    return render_template('user/reset_token.html')

@users.route('/users/signup', methods=['GET', 'POST'])
def sign_up():
    if  session.get('user_id'):
        return redirect('/users/dashboard')

    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(username=username).first()
        email_address = User.query.filter_by(email=email).first()

        if user:
          flash('Username already exists.', category='warning')
        elif email_address:
          flash('Email already exists.', category='warning')
        elif len(username) < 2:
            flash('Username must be more than 1 characters.', category='warning')
        elif len(email) < 4:
            flash('Email must be more than 4 characters.', category='warning')
        elif password1 != password2:
            flash('Password don\'t match.', category='warning')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='warning')
        else:
            # add user to database
            new_user = User(username=username, 
                                email=email, 
                                password=generate_password_hash(
                                password1, 
                                method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            
            send_confirmation_email(new_user)
            
            flash('Success. Account created!', category='success')
            return redirect(url_for('users.register'))
    
    return render_template('user/signup.html')

@users.route('/users/register', methods=['GET', 'POST'])
@login_required
def register():
    if  session.get('user_id'):
        return redirect('/users/dashboard')
    
    user = current_user.id

    if request.method == 'POST':
        idno = request.form.get('idno')
        fullname = request.form.get('fullname')
        phonenumber = request.form.get('phonenumber')
        residence = request.form.get('residence')
        gender = request.form.get('gender')
        
        new_idno = Register.query.filter_by(idno=idno).first()
        
        new_phonenumber = Register.query.filter_by(phonenumber=phonenumber).first()

        if len(idno) < 8 or len(idno) > 8:
            flash('Identification Number must be equal to 8 characters.', category='warning')
        elif new_idno:
            flash('Identification number already exist', category='warning')
        elif len(fullname) < 4:
            flash('Full Name must be more than 4 characters.', category='warning')
        elif len(phonenumber) < 10 or len(phonenumber) > 10:
            flash('Invalid Phone number', category='warning')
        elif new_phonenumber:
            flash('Phone number already exists', category='warning')        
        else:
            personal_details = Register(idno=idno, 
                                    fullname=fullname, 
                                    phonenumber=phonenumber, 
                                    residence=residence, 
                                    gender=gender,
                                    users_id=user)
            db.session.add(personal_details)
            db.session.commit()
            flash(f"Hello, {fullname}, Login to Access the Dashboard", category='success')
            return redirect(url_for('users.user_dashboard'))

    return render_template('user/register.html')

@users.route('/users/signout')
@login_required
def sign_out():
    if not session.get('user_id'):
        return redirect(url_for('users.sign_in'))
    
    if session.get('user_id'):
        session['user_id'] = None
        session['username'] = None
        flash('You have been logged out.', category='info')
        logout_user()
    return redirect(url_for('users.sign_in'))
    
# getting coordinates
@users.route('/save-coordinates', methods=['POST'])
def save_coordinates():
    data = request.get_json()
    session['latitude'] = data['latitude']
    session['longitude'] = data['longitude']
    return 'Coordinates saved', 200


@users.route('/users/dashboard', methods=['GET', 'POST'])
@login_required
def user_dashboard(): 
    news_api = environ.get('NEWS_API')
    user_id = session.get('user_id')
    latitude = session.get('latitude')
    longitude = session.get('longitude')
    print(latitude)
    print(longitude)
    if user_id:
        user = User.query.get(user_id)
        if user:
            login_user(user)   

            url = f'https://newsapi.org/v2/top-headlines?country=us&category=general&apiKey={news_api}'

            try:
                response = requests.get(url)
                response.raise_for_status()
                news_data = response.json()
                articles = news_data.get('articles', [])
            except RequestException:
                flash("Error fetching news. Try connecting to internet", category='danger')
                articles = []

            return render_template('user/userdashboard.html', articles=articles, latitude=latitude, longitude=longitude)
        else:
            session.clear()
            return redirect('/users/signin')
    else:
        return redirect('/users/signin')
        
@users.route('/users/history')
@login_required
def history():
    try:
        reporter = current_user.id

        crimes = Crime.query.filter_by(reporter_id=reporter).all()

        return render_template('user/history.html', crimes=crimes)
    
    except Exception:
        flash('Unable to fetch your data. Please try again later.', 'danger')
        return render_template('user/history.html', crimes=[])


@users.route('/users/recovered-items')
@login_required
def recovered():
    try:
        recovered_crimes = Crime.query.filter_by(crime_status='Recovered').all()
    except:
        flash("An error occurred while fetching crime details. Please try again later.", "danger")
        return redirect(url_for('users.recovered'))
    
    return render_template('user/recovered_items.html', recovered_crimes=recovered_crimes)

# DOWNLOADING P3 FORM
@users.route('/users/downloads', methods=['GET', 'POST'])
@login_required
def download():
    if request.method == 'POST':
        filename = "P3.pdf"  
        directory = os.path.join(current_app.root_path, 'static', 'files')
        
        if os.path.exists(os.path.join(directory, filename)):
            return send_from_directory(directory, filename, as_attachment=True)
        else:
            flash('Unable to download file', 'warning')
            return redirect(url_for('users.download'))
        
    return render_template('user/downloads.html')

app/templates/user/change-password.html
{% extends 'user/base.html' %} {% block content %}
<style>
  /* body {
    background-color: #ececec;
  } */
</style>
<body class="my-login-page">
  <section class="h-100">
    <div>
      <div class="row justify-content-md-center h-100">
        <div class="card-wrapper">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages%}
          <div
            class="alert alert-{{ category }} alert-dismissible fade show"
            role="alert"
          >
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
            {{ message }}
          </div>
          {% endfor %} {% endif%} {% endwith %}
          <div class="card fat">
            <div class="card-body">
              <h4 class="card-title" align="center">User Change Password</h4>
              <form method="POST">
                <div id="msg">{{ msg }}</div>
                <div class="form-group">
                  <label for="">Enter Email:</label>
                  <input
                    id="email"
                    type="text"
                    class="form-control"
                    placeholder="Email"
                    name="email"
                  />
                </div>
                <br />
                <div class="form-group">
                  <label for="">Enter New Password: </label>
                  <input
                    id="password"
                    type="password"
                    class="form-control"
                    name="password"
                    placeholder="New password"
                    data-eye
                  />
                </div>
                <br />
                <div class="form-group m-0">
                  <button class="btn btn-success" name="userChangePassword">
                    Submit
                  </button>
                  <a href="{{ url_for('users.settings') }}"
                    ><button type="button" class="btn btn-primary">
                      Back
                    </button></a
                  >
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
{% endblock content %}

app/templates/user/contactus.html
{% extends 'user/base.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Contact Us</title>
    <style>
      body {
        /* background-color: #f0f0f0; */
        margin-top: 40px;
      }
      #contactForm {
        background-color: white;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        max-width: 500px;
        margin: 0 auto;
      }
      h2 {
        margin-top: 0;
        margin-bottom: 5px;
        color: #333;
        font-size: 24px;
        text-align: center;
        font-weight: bold;
      }
      p {
        text-align: center;
        color: #666;
        font-size: 14px;
        margin-top: 0;
        margin-bottom: 20px;
      }
      .form-group {
        margin-bottom: 20px;
      }
      label {
        display: block;
        margin-bottom: 5px;
        color: #333;
        font-size: 14px;
      }
      input,
      textarea {
        width: 100%;
        padding: 8px;
        border: 1px solid #ddd;
        border-radius: 4px;
        box-sizing: border-box;
        font-size: 14px;
      }
      .name-inputs {
        display: flex;
        gap: 10px;
      }
      .name-inputs input {
        flex: 1;
      }
      textarea {
        resize: vertical;
        min-height: 100px;
      }
      .button-group {
        display: flex;
        gap: 10px;
      }
      button {
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        flex: 1;
      }
      .submit-btn {
        background-color: #007bff;
        color: white;
        border: none;
      }
      .back-btn {
        background-color: #f0f0f0;
        color: #333;
        border: 1px solid #ddd;
      }
      button:hover {
        opacity: 0.8;
      }
      .required {
        color: red;
      }
    </style>
  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages%}
    <div
      class="alert alert-{{ category }} alert-dismissible fade show"
      role="alert"
    >
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
      {{ message }}
    </div>
    {% endfor %} {% endif%} {% endwith %}
    <form id="contactForm" method="POST">
      <h2>Contact Us</h2>
      <p>Send us a message</p>

      <div class="form-group">
        <label for="fullName">Full Name <span class="required">*</span></label>
        <div class="name-inputs">
          <input
            type="text"
            id="firstName"
            name="firstName"
            placeholder="First Name"
            required
          />
          <input
            type="text"
            id="lastName"
            name="lastName"
            placeholder="Last Name"
          />
        </div>
      </div>

      <div class="form-group">
        <label for="email">E-mail <span class="required">*</span></label>
        <input
          type="email"
          id="email"
          name="email"
          placeholder="example@example.com"
          required
        />
      </div>

      <div class="form-group">
        <label for="message">Message <span class="required">*</span></label>
        <textarea id="message" name="message" required></textarea>
      </div>

      <div class="button-group">
        <a href="{{ url_for('users.user_dashboard') }}"
          ><button type="button" class="back-btn">
            <i class="bi bi-arrow-left-circle-fill"></i></button
        ></a>
        <button type="submit" name="contact_us" class="submit-btn">
          SUBMIT
        </button>
      </div>
      <br />
      <p><strong>You may also call us at: +254712345678</strong></p>
    </form>
  </body>
</html>
{% endblock content %}

app/templates/user/crime-details.html
{% extends 'user/base.html' %}
{% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Crime Details</title>
  <link rel="stylesheet" href="./include/footer.css">

  <style>
      /* body {
          font-family: Arial, sans-serif;
          background-color: #f8f9fa;
          margin: 0;
          padding-bottom: 60px; /* Adjust for footer height
      }*/

      form {
          max-width: 800px;
          margin: 20px auto; /* Adjust margin */
          padding: 20px;
          background-color: #fff;
          border-radius: 10px;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
          overflow: hidden; /* Prevent button overlap */
      }

      .form-column {
          float: left;
          width: 50%;
          padding-right: 20px;
          box-sizing: border-box;
      }

      .form-row:after {
          content: "";
          display: table;
          clear: both;
      }

      label {
          display: block;
          margin-bottom: 5px;
          font-weight: bold;
      }

      input[type="text"],
      input[type="number"],
      textarea,
      input[type="date"],
      button {
          width: calc(100% - 22px);
          padding: 10px;
          margin-bottom: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          box-sizing: border-box;
          font-size: 16px;
      }
      textarea {
          height: 150px; 
      }

      button {
          background-color: #007bff;
          color: #fff;
          border: none;
          cursor: pointer;
          padding: 8px 16px;
          font-size: 16px; 
          width: auto; 
          display: block; 
          margin: 0 auto;
          float: right; /* Align to right */
      }

      button.info {
          background-color: #17a2b8;
          float: left; /* Align to left */
          margin-right: 10px; /* Add margin between buttons */
      }

      button.info:hover {
          background-color: #137887;
      }

      button.submit:hover {
          background-color: #056ad5;
      }

      @media (max-width: 768px) {
          .form-column {
              width: 50%; /* Switch to two columns on smaller screens */
              padding: 20px; /* Add padding for better spacing */
          }

          .form-row {
              display: flex; /* Make rows display flexibly */
              flex-wrap: wrap; /* Allow rows to wrap */
          }
      }
      h1 {
        text-align: center;
      }
      #imagePreview {
      max-width: 100%;
      height: auto;
      margin-top: 15px;
      border: 1px solid #ddd;
      padding: 5px;
      border-radius: 5px;
      }
      .image-container {
          position: relative;
          max-width: 50%;
          height: auto;
      }

      #imagePreview, #videoPreview {
          max-width: 100%;
          height: auto;
      }

      #cancelButton {
          position: absolute;
          top: 0;
          left: 0;
          z-index: 1000;
      }
      .printer-button {
        background: none;
        border: none;
        cursor: pointer;
        color: black;
    }
    @media print {
        body { font-size: 12pt; }
        button { display: none; }
    }
    .evidence-container {
        max-width: 300px;
    }
    .download-button {
        width: 100%;
        font-size: 0.9rem;
        display: block;
        text-align: center;
        margin-top: 10px;
    }
  </style>
</head>
<body>
  <!-- {% for crime_details in crime_details %} -->
  <form method="POST, GET">
    <div class="ms-auto">
        <button class="printer-button" onclick="window.print()"><i class="bi bi-printer h4"></i></button> 
     </div>
    <h1 style="text-align: left;"><strong>Report On: {{ crime_details.incident_nature }}</strong></h1>
    <div class="form-row">
        <div class="form-column">
            <label for="date_of_incident">Date when incident occurred</label>
            <input type="date" id="date_of_incident" name="date_of_incident" value="{{ crime_details.date_of_incident }}" readonly>

            <label for="issued_by">Incident reported by</label>
            <input type="text" id="issued_by" name="issued_by" value="{{ crime_details.issued_by }}" readonly>

            <label for="status">Status</label>
            <input type="text" id="status" name="status" value="{{ crime_details.crime_status }}" readonly>
        </div>

        <div class="form-column">
            <label for="time_of_incident">Time when incident occurred</label>
            <input type="text" id="time_of_incident" name="time_of_incident" value="{{ crime_details.time_of_incident }}" readonly>

            <label for="date_received">Received On</label>
            <input type="text" id="date_received" name="date_received" value="{{ crime_details.date_crime_received.strftime('%Y-%m-%d %H:%M') }}" readonly>

            <label for="phonenumber">Phone Number</label>
            <input type="text" id="phonenumber" name="phonenumber" value="{{ crime_details.phonenumber }}" readonly>
        </div>
    </div>

    <div class="form-row">
        <label for="incident_location">Incident location:</label>
        <textarea id="incident_location" name="incident_location" value="" style="width: calc(100% - 22px);" readonly>{{ crime_details.incident_location }}</textarea>
    </div>

    <div class="form-row">
        <label for="incident_nature">Nature of incident:</label>
        <textarea id="incident_nature" name="incident_nature" style="width: calc(100% - 22px);" readonly>{{ crime_details.incident_nature }}</textarea>
    </div>

    <div class="form-row">
      <label for="incident_details">More Details</label>
      <textarea id="incident_details" name="incident_details" style="width: calc(100% - 22px);" readonly>{{ crime_details.incident_details }}</textarea>
    </div>

    <div class="form-row">
      <label for="suspect_details">Suspect History</label>
      <textarea id="suspect_details" name="suspect_details" style="width: calc(100% - 22px);" readonly>{{ crime_details.suspect_details }}</textarea>
    </div>

    <div class="form-row">
      <label for="arrest_history">Arrest in relation to Incident</label>
      <textarea id="arrest_history" name="arrest_history" style="width: calc(100% - 22px);" readonly>{{ crime_details.arrest_history }}</textarea>
    </div>
    <hr>
    <label for="suspect_name">Suspect Name:</label>
    <input type="text" id="suspect_name" name="suspect_name" value="{{ crime_details.suspect_name }}">

    <div class="form-row">
      <label for="comments">Further Comments</label>
      <textarea id="comments" name="comments" style="width: calc(100% - 22px);" readonly>{{ crime_details.comments }}</textarea>
    </div>

    <div class="form-group evidence-container">
        <label for="mediaUpload">Attached Evidence:</label>
        {% if crime_details.crime_file_upload %}
            <img src="{{ url_for('users.download_image', crime_id=crime_details.crime_id) }}" alt="{{ crime_details.crime_file_name }}" class="img-fluid">
            <a href="{{ url_for('users.download_image', crime_id=crime_details.crime_id) }}" class="btn btn-primary download-button" download>
                <i class="bi bi-download"></i> Download
            </a>
        {% else %}
            <p>No attached evidence.</p>
        {% endif %}
    </div>
  </br>
    <div class="form-row">
        <a href="{{ url_for('users.history') }}"><i class="bi bi-arrow-left-circle-fill h4"></i></a>
    </div>
  </form>
<!-- {% endfor %} -->
<script>
  
</script>
</body>
{% endblock content %}

app/templates/user/notification.html
{% extends "user/base.html" %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Notification Cards</title>
    <style>
      body {
        margin: 0;
        padding: 40px;
        /* background-color: #ececec; */
      }
      .notification-container {
        max-width: 100%;
        margin: 0 auto;
        padding: 20;
      }
      .notification-card {
        background-color: rgba(255, 255, 255, 0.698);
        border-radius: 8px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        margin-bottom: 15px;
        overflow: hidden;
        transition: box-shadow 0.3s ease;
      }
      .notification-card:hover {
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
      }
      .notification-link {
        display: block;
        padding: 20px;
        color: inherit;
        text-decoration: none;
      }
      .notification-title {
        font-size: 14px;
        margin-bottom: 5px;
      }
      .notification-description {
        font-size: 14px;
        color: #666;
      }
      .notification-time {
        font-size: 12px;
        color: #999;
        margin-top: 10px;
      }
      h1 {
        text-align: center;
      }
    </style>
  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages%}
    <div
      class="alert alert-{{ category }} alert-dismissible fade show"
      role="alert"
    >
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
      {{ message }}
    </div>
    {% endfor %} {% endif%} {% endwith %}
    <h1>Notifications</h1>

    {% if user_message %}
    <div class="notification-container">
      {% for message in user_message %}
      <div class="notification-card" data-notification-id="{{ message.id }}">
        <a href="{{ url_for('users.notification')}}" class="notification-link">
          <h6 style="font-weight: bold">You:</h6>
          <div class="notification-title">{{ message.message }}</div>
          <h6 style="font-weight: bold">Admin:</h6>
          <div class="notification-description">{{ message.reply }}</div>
        </a>
      </div>
    </div>
    {% endfor %} {% else %}
    <h3 style="text-align: center">
      <i class="bi bi-envelope-x-fill h2"></i> No Notifications.
    </h3>
    {% endif %}
    <script></script>
  </body>
</html>
{% endblock content %}

app/templates/user/signin.html
{% extends "user/base.html" %} {% block title %} SignIn {% endblock %} {% block
content %}
<body class="my-login-page">
  <section class="h-100">
    <div>
      <div class="row justify-content-md-center h-100">
        <div class="card-wrapper">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages%}
          <div
            class="alert alert-{{ category }} alert-dismissible fade show"
            role="alert"
          >
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
            {{ message }}
          </div>
          {% endfor %} {% endif%} {% endwith %}
          <div class="card fat">
            <div class="card-body">
              <h5 class="card-title" align="center">User Login</h5>
              <form method="POST">
                <div id="msg">{{ msg }}</div>
                <div class="form-group">
                  <label for="username" class="form-label">Username</label>
                  <input
                    id="username"
                    type="username"
                    class="form-control"
                    name="username"
                    placeholder="Username"
                    required
                  />
                </div>
                <br />
                <div class="form-group">
                  <label for="password" class="form-label">Password </label>
                  <input
                    id="password"
                    type="password"
                    class="form-control"
                    name="password"
                    placeholder="Password"
                    required
                    data-eye
                  />
                </div>
                <p style="text-align: right;">
                  <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </p>
                <div class="form-group m-0" align="center">
                  <button
                    type="submit"
                    class="btn btn-primary btn-block w-100 btn-sm px-3 py-2"
                    href="{{ url_for('users.user_dashboard') }}"
                  >
										<i class="bi bi-box-arrow-in-right"></i>
                    Login
                  </button>
                </div>
              </form>
            </div>
          </div>
          <div class="mt-4 text-center">
            <i class="bi bi-person-add"></i> Don't have an account?
            <a href="{{ url_for('users.sign_up') }}">Register</a>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
{% endblock %}